export const database = {
    attractions: [
        { id: 'dai_noi', name: 'Đại Nội Huế', image: 'images/dai_noi.jpg', description: 'Đại Nội Huế là trung tâm của Quần thể di tích Cố đô Huế, một công trình kiến trúc đồ sộ và độc đáo. Nơi đây từng là nơi ở và làm việc của 13 vị vua triều Nguyễn. Khám phá các cung điện, đền đài và miếu thờ nguy nga như Điện Thái Hòa, Tử Cấm Thành, và Thế Miếu để cảm nhận sự uy nghiêm và vẻ đẹp vàng son một thời.' },
        { id: 'chua_thien_mu', name: 'Chùa Thiên Mụ', image: 'images/chua_thien_mu.jpg', description: 'Là biểu tượng của xứ Huế, chùa Thiên Mụ nằm trên đồi Hà Khê, soi bóng xuống dòng sông Hương thơ mộng. Ngôi chùa nổi bật với tháp Phước Duyên 7 tầng cao vút. Không gian thanh tịnh, tiếng chuông chùa ngân vang và những câu chuyện lịch sử bí ẩn làm cho nơi đây trở thành điểm đến không thể bỏ qua.' },
        { id: 'lang_khai_dinh', name: 'Lăng Khải Định', image: 'images/lang_khai_dinh.jpg', description: 'Lăng Khải Định (Ứng Lăng) là công trình kiến trúc độc đáo bậc nhất trong các lăng tẩm ở Huế. Với sự kết hợp tinh xảo giữa kiến trúc Đông - Tây, lăng được xây dựng bằng các vật liệu hiện đại như bê tông, thép nhưng được trang trí bằng những mảnh sành sứ, thủy tinh ghép vô cùng công phu. Đây là một tác phẩm nghệ thuật tuyệt đẹp, thể hiện cá tính của vị vua thứ 12 triều Nguyễn.' },
        { id: 'song_huong', name: 'Sông Hương', image: 'images/song_huong.jpg', description: 'Sông Hương là linh hồn của Huế, một dòng sông hiền hòa chảy qua lòng thành phố. Trải nghiệm tuyệt vời nhất là du thuyền trên sông vào buổi tối, ngắm cầu Trường Tiền sáu vài mười hai nhịp rực rỡ sắc màu, và lắng nghe những làn điệu ca Huế sâu lắng, trữ tình. Đây là cách tốt nhất để cảm nhận trọn vẹn sự lãng mạn của Cố đô.' },
        { id: 'lang_minh_mang', name: 'Lăng Minh Mạng', image: 'images/lang_minh_mang.jpg', description: 'Lăng Minh Mạng (Hiếu Lăng) được xem là một trong những lăng tẩm đẹp và uy nghiêm nhất. Với 40 công trình lớn nhỏ được bố trí đối xứng trên một trục thần đạo, lăng là một tổng thể kiến trúc hài hòa giữa con người và thiên nhiên. Hồ sen, những cây cầu đá và các công trình điêu khắc tinh xảo tạo nên một không gian vừa trang nghiêm vừa thơ mộng.' },
    ],
    cuisine: [
        { id: 'bun_bo_hue', name: 'Bún bò Huế', image: 'images/bun_bo_hue.jpg', description: 'Không chỉ là một món ăn, bún bò Huế là một phần văn hóa của Cố đô. Một tô bún bò đúng điệu có nước dùng đậm đà vị xương hầm và mắm ruốc, sợi bún to, những miếng thịt bò, chả cua, và tiết heo. Vị cay nồng của ớt, hương thơm của sả và các loại rau sống tạo nên một bản giao hưởng hương vị khó quên.' },
        { id: 'nem_lui', name: 'Nem lụi', image: 'images/nem_lui.jpg', description: 'Nem lụi là món ăn vặt đặc sản không thể bỏ qua. Thịt heo xay nhuyễn được quấn quanh những cây sả, sau đó nướng trên than hồng cho đến khi vàng ruộm và dậy mùi thơm. Nem lụi được ăn kèm với bánh tráng, rau sống, và một loại nước lèo đặc biệt làm từ gan heo, đậu phộng, tạo nên hương vị béo ngậy, đậm đà.' },
        { id: 'banh_beo', name: 'Bánh bèo, Nậm, Lọc', image: 'images/banh_beo.jpg', description: 'Đây là bộ ba món bánh tráng miệng tinh túy của ẩm thực Huế. Bánh bèo được hấp trong những chiếc chén nhỏ, với tôm cháy và da heo chiên giòn. Bánh nậm mềm mại, được gói trong lá dong. Bánh lọc trong veo, dai dai với nhân tôm thịt. Cả ba đều được thưởng thức với nước mắm chua ngọt, tạo nên một trải nghiệm ẩm thực tinh tế.' },
        { id: 'com_hen', name: 'Cơm Hến', image: 'images/com_hen.jpg', description: 'Cơm hến là một món ăn dân dã nhưng vô cùng đặc sắc. Một tô cơm hến bao gồm cơm nguội, hến xào, tóp mỡ, mắm ruốc, rau sống, và đậu phộng. Khi ăn, tất cả được trộn đều với một ít nước luộc hến nóng hổi. Vị ngọt của hến, vị cay của ớt, và sự tươi mát của rau tạo nên một món ăn độc đáo và hấp dẫn.' },
        { id: 'che_hue', name: 'Chè Huế', image: 'images/che_hue.jpg', description: 'Huế được mệnh danh là "kinh đô của các loại chè". Từ những loại chè cung đình cầu kỳ như chè hạt sen long nhãn đến những loại chè dân dã như chè bắp, chè khoai, chè bột lọc heo quay... Mỗi loại chè là một tác phẩm nghệ thuật nhỏ, mang một hương vị riêng, thể hiện sự khéo léo và tinh tế trong ẩm thực của người Huế.' },
    ],
    homestays: [
        { id: 'homestay_a', name: 'Homestay Riverside', image: 'images/homestay_a.jpg', description: 'Tọa lạc bên bờ sông Như Ý thơ mộng, Riverside Homestay mang đến một không gian yên bình và thư thái. Với kiến trúc cổ điển kết hợp hiện đại, các phòng nghỉ đều có ban công nhìn ra sông. Đây là nơi lý tưởng để bạn thư giãn, đọc sách và ngắm hoàng hôn buông xuống trên mặt nước.' },
        { id: 'homestay_c', name: 'Ancient Hue Garden Houses', image: 'images/homestay_c.jpg', description: 'Đây không chỉ là một nơi ở, mà là một trải nghiệm văn hóa. Bạn sẽ được nghỉ dưỡng trong những ngôi nhà rường cổ truyền của Huế, được phục dựng và trang bị tiện nghi hiện đại. Ancient Hue còn có nhà hàng phục vụ các món ăn cung đình, mang đến cho bạn một kỳ nghỉ vương giả và độc đáo.' },
        { id: 'deja_vu', name: 'Deja Vu Homestay', image: 'images/deja_vu.jpg', description: 'Deja Vu mang một phong cách trang trí vintage độc đáo, với những món đồ nội thất cổ và các góc decor đầy hoài niệm. Homestay tạo ra một không gian ấm cúng, gần gũi như ở nhà. Vị trí thuận lợi, gần các quán ăn ngon và các điểm tham quan là một điểm cộng lớn.' },
    ],
    cafes: [
        { id: 'cafe_b', name: 'An Nhien Garden Cafe', image: 'images/cafe_b.jpg', description: 'An Nhiên là một không gian sân vườn rộng lớn, yên tĩnh và tách biệt khỏi sự ồn ào của phố thị. Với nhiều cây xanh, hồ cá Koi, và những góc ngồi riêng tư, đây là nơi hoàn hảo để bạn tìm kiếm sự bình yên, đọc một cuốn sách hay trò chuyện cùng bạn bè.' },
        { id: 'tan_cafe', name: 'Tân Cafe', image: 'images/tan_cafe.jpg', description: 'Tân Cafe là điểm đến không thể bỏ lỡ cho những người yêu thích cafe rang xay chất lượng cao. Quán có không gian thiết kế tối giản, hiện đại và tập trung vào trải nghiệm thưởng thức cafe. Bạn có thể quan sát quá trình pha chế và trò chuyện cùng các barista am hiểu.' },
        { id: 'mat_biec', name: 'Mắt Biếc Cafe', image: 'images/mat_biec.jpg', description: 'Được lấy cảm hứng từ bộ phim nổi tiếng "Mắt Biếc" của đạo diễn Victor Vũ, quán cafe này tái hiện lại không gian làng quê Việt Nam xưa với những góc nhà cổ, hàng hiên và những chi tiết trang trí hoài niệm. Đây là một địa điểm check-in cực kỳ nổi tiếng và thu hút giới trẻ.' },
    ],
}; 